<html>
    <head>
        <!-- BASE -->
        <base href="/">
        <title><?= $_GET['page_title'] ?> | Happietaria</title>


        <!-- meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="">


        <!-- favicon
            <link rel="shortcut icon" type="image/png" href="/template/images/favicon.png"/>
            <link rel="icon" type="image/ico" href="template/_img/logo_small.ico"/>
        -->


        <!-- jQuery -->
        <script src="/template/_js/jquery-3.2.1.min.js"></script>
        <script src="/template/_js/materialize.min.js"></script>


        <!-- Materialize -->
        <link href="/template/_css/materialize.min.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


        <!-- eigen stylesheets -->
        <?= '<link href="/template/_css/'.$_GET["template"].'.css" rel="stylesheet" />'; ?>

    </head>
    <body>
            <?php
                // Head
                if($_GET["page_header"]) {
                    include('template/headers/'.$_GET["template"].'.phtml');
                }

                // body
                echo $content;
                if($_GET["page_footer"]) {
                    include('template/footers/' . $_GET["template"] . '.phtml');
                }
            ?>

    </body>


    <!-- Eigen JS -->
    <script src="template/_js/base.js"></script>
</html>