<?php
    $r =  $this->obj->data["reservation"];
    $r["reservering"] = new DateTime($r["reservering"]);

?>
<br />
<div class="container">
    <div class="row">
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <a href="/reservering/index" class="btn orange darken-2">NAAR OVERZICHT</a>
                </div>
            </div>
        </div>
        <div class="col s6">
            <div class="card" style="height: 550px">
                <div class="card-content">

                    <h3>Reservering #<?= $r["reservering_id"] ?></h3>
                    <br />
                    <table class="table bordered">
                        <tr>
                            <th>Status:</th>
                            <td>
                                <div style="margin-bottom: -30px">
                                    <?= $r["naam"] ?>
                                </div>

                            </td>
                        </tr>
                        <tr>
                            <th>Geaccepteerd:</th>
                            <td><?php
                                switch($r["geaccepteerd"]){
                                    case 0: echo "<b style='color: #ff9800 '>Nog niet beoordeeld</b>";break;
                                    case 1: echo "<b style='color: #0c0'>Ja</b>";break;
                                    case 2: echo "<b style='color: #c00'>Nee</b>";break;
                                }
                            ?></td>
                        </tr>
                        <tr>
                            <th>Aantal personen:</th>
                            <td><b><?= $r["personen"] ?></b> personen</td>
                        </tr>
                        <tr>
                            <th>Datum:</th>
                            <td><?= $r["reservering"]->format('d F Y') ?></td>
                        </tr>
                        <tr>
                            <th>Tijd:</th>
                            <td><?= $r["reservering"]->format('H:i') ?></td>
                        </tr>
                        <tr>
                            <th>Opmerking:</th>
                            <td><i><?= $r["opmerking"] ?></i></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col s6">
            <div class="card"  style="height: 550px">
                <div class="card-content">
                    <h3>Aangemaakt door:</h3>
                    <br />
                    <table class="table bordered">
                        <tr>
                            <th>Naam:</th>
                            <td><?= $r["voornaam"] . ' ' . $r["achternaam"] ?></td>
                        </tr>
                        <tr>
                            <th>Email:</th>
                            <td><a href="mailto:<?= $r["email"] ?>"><?= $r["email"] ?></a></td>
                        </tr>
                        <tr>
                            <th>Telefoon:</th>
                            <td><?= $r["telefoon"] ?></td>
                        </tr>
                    </table>

                </div>
            </div>
        </div>
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <form action="/reservering/sendmail/<?=$_GET["id"] ?>" method="post">
                        <input type="submit" name="JUDGE" value="ACCEPT" class="btn green darken-1 right" style="margin-left: 10px"/>
                        <input type="submit" name="JUDGE" value="REFUSE" class="btn  red  darken-3 right"/>
                    </form>

                    <div style="clear:both"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>