<br />
<div class="container">
    <div class="card">
        <div class="card-content">
            <?php
            foreach($this->obj->data["states"] as $s){
                //if($s["status_id"] == $_GET["id"]){  $curState = $s["naam"]; } else { $class = "waves-effect waves-teal btn-flat"; }
                $class = ($s["status_id"] == $_GET["id"]) ? "waves-effect light-blue darken-3 waves-light btn" :"waves-effect waves-teal btn-flat"  ;
                $items = ($s["items"] >= 1 && $s["status_id"] != 4) ? '<div class="blue lighten-1" style="color: #fff; padding: 2px 8px; line-height: 15px; margin-left: 8px; margin-top: 8px; border-radius: 20px; font-size: 10px; float: left ">'.$s["items"].'</div>' : "" ;
                echo '<a href="/reservering/index/'.$s["status_id"].'" class="'.$class.'"><p style="float: left;">'.$s["naam"].'</p> '.$items.'</a>';



            }


            ?>
            <a href="/reservering/calendar/<?= date('Y-m-d') ?>" class="btn-floating right  green darken-2" style="margin-left: 8px;"><i class="material-icons">date_range</i></a>
            <a href="/reservering/statussen" class="btn-floating right  red darken-3" ><i class="material-icons">build</i></a>
            <br />
            <br />
            <br />
            <hr />
            <br />
            <br />
            <h4>Reserveringen</h4>

            <table  class="table">
                <thead>
                    <th>#</th>
                    <th>Naam</th>
                    <th>Datum</th>
                    <th>Shift</th>
                    <th>Geaccepteerd</th>
                    <th></th>
                </thead>
                <tbody>
                    <?php
                        foreach($this->obj->data["reservations"] as $r){
                            $geaccepteerd = ($r["geaccepteerd"] == 0) ? false : true;
                            $chgAcc = "";
                            switch($r["geaccepteerd"]){
                                case 0: $r["geaccepteerd"] = "Nog niet behandeld";break;
                                case 1: $r["geaccepteerd"] = "<b style='color: #0c0'>Ja</b>";   $chgAcc = '| <a href="/reservering/accept/' . $r["reservering_id"] . '">Weigeren</a> ';break;
                                case 2: $r["geaccepteerd"] = "<b style='color: #c00'>Nee</b>";  $chgAcc = '| <a href="/reservering/accept/' . $r["reservering_id"] . '">Accepteren</a> ';break;
                            }


                            $r["datum"] = new DateTime($r["datum"]);
                            echo '<tr>';
                                echo '<td>#'.$r["reservering_id"].'</td>';
                                echo '<td>'.$r["voornaam"].' '.$r["achternaam"].'</a></td>';
                                echo '<td>'.$r["datum"]->format('d F Y').'</td>';
                                echo '<td>'.$r["shift"].'</td>';
                                echo '<td>'.$r["geaccepteerd"].'</td>';

                                echo '<td style="text-align: right; min-width: 80px !Important">';
                                    if($geaccepteerd) {
                                       // echo '<a href="reservering/bekijken/' . $r["reservering_id"] . '">Bekijken</a> | ';
                                        //echo '<a href="/reservering/index">Beantwoorden</a>';
                                        echo '<a href="/reservering/bekijken/' . $r["reservering_id"] . '">Details</a> ';
                                        echo $chgAcc;
                                        if($_GET["id"] != 4){echo '| <a href="/reservering/archive/' . $r["reservering_id"] . '">Archiveren</a>';}
                                    }else{
                                        echo '<a class="btn green darken-1" href="/reservering/beoordelen/' . $r["reservering_id"] . '">beoordelen</a>';
                                    }
                                echo '</td>';
                            echo '<tr>';
                        }
                        if($this->obj->data["reservations"] == null){
                            echo '<tr><td><b style="color: #999">#0</b></td><td colspan="3"><i style="color: #999; font-weight: bold;">No records found</i></td></tr>';
                        }

                    ?>

                </tbody>
            </table>
            <br /><br />
            <br /><br />
        </div>
    </div>
</div>