<?php
$r =  $this->obj->data["reservation"];
$m =  $this->obj->data["mail"];
$r["reservering"] = new DateTime($r["reservering"]);

?>
<br />
<div class="container">
    <form action="" method="post">
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        <a href="/reservering/index" class="btn orange darken-2">NAAR OVERZICHT</a>
                    </div>
                </div>
            </div>
            <div class="col s12">
                <div class="card" style="min-height: 550px">
                    <div class="card-content">

                        <h3>De klant informeren</h3>
                        <?= $this->obj->data["message"]; ?>

                        <br />

                        <div class="row">
                            <div class="input-field col s12">
                                <input placeholder="Typ hier het onderwerp van de mail" value="<?=  $m["subject"] ?>" type="text" id="onderwerp" name="onderwerp" class="validate">
                                <label for="onderwerp">ONDERWERP</label>
                            </div>
                        </div>

                        <div class="row">
                            <div class="input-field col s12">
                                <textarea style="min-height: 250px; background: #eee; box-sizing: border-box; padding: 15px;" id="message" name="inhoud" class="materialize-textarea"><?= $m["message"];  ?></textarea>
                                <label for="message">INHOUD VAN DE MAIL</label>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        <form action="/reservering/sendmail/<?=$_GET["id"] ?>" method="post">
                            <button type="submit" name="confirmation" value="mailOk" class="btn green darken-1 right" style="margin-left: 10px">Send mail</button>
                        </form>

                        <div style="clear:both"></div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
