<?php
$r =  $this->obj->data["reservation"];
$r["datum"] = new DateTime($r["datum"]);

?>
<br />
<div class="container">
    <form action="" method="post">
        <div class="row">

            <div class="col s6">
                <div class="card" style="height: 650px">
                    <div class="card-content">
                        <h4>Details  </h4>

                        <?= $this->obj->data["message"]; ?>

                        <br />
                        <table class="table bordered">

                            <tr>
                                <th>Status:</th>
                                <td>
                                    <div style="margin-bottom: -30px">
                                        <select class="form-control" name="status" style="height: 30px;">
                                            <?php
                                            foreach($this->obj->data["status"] as $status){
                                                if($status["naam"] == $r["naam"]){
                                                    echo '<option value="'.$status["status_id"].'" selected>'.$status["naam"].'</option>';
                                                }else{
                                                    echo '<option value="'.$status["status_id"].'">'.$status["naam"].'</option>';
                                                }
                                            }
                                            ?>
                                        </select>
                                    </div>

                                </td>
                            </tr>
                            <tr>
                                <th>Reservering ID</th>
                                <td><b>#<?= $r["reservering_id"] ?></b></td>
                            </tr>
                            <tr>
                                <th>Geaccepteerd:</th>
                                <td><?php
                                    switch($r["geaccepteerd"]){
                                        case 0: echo "<b style='color: #ff9800 '>Nog niet beoordeeld</b>";break;
                                        case 1: echo "<b style='color: #0c0'>Ja</b>";break;
                                        case 2: echo "<b style='color: #c00'>Nee</b>";break;
                                    }
                                    ?></td>
                            </tr>
                            <tr>
                                <th>Aantal personen:</th>
                                <td>
                                    <div style="margin-bottom: -30px;margin-top: -10px;">
                                        <input type="number" style="width:50px; height: 30px; text-align: center;" name="personen" value="<?= $r["personen"] ?>" /> <b>personen</b>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <th>Datum:</th>
                                <td>
                                    <div style="margin-bottom: -30px">
                                        <input type="date" style="height: 30px;" name="date" value="<?= $r["datum"]->format('Y-m-d') ?>"/>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <th>Kies een shift:</th>
                                <td>
                                    <div style="margin-bottom: -30px">
                                        <select class="form-control" name="shift" >
                                            <?php
                                            foreach($this->obj->data["shifts"] as $v){
                                                $bg_tijd = new DateTime($v["begin_tijd"]);
                                                $ed_tijd = new DateTime($v["eind_tijd"]);
                                                $selected = ($v["shift_id"] == $r["shift_id"]) ? "selected" : "";
                                                echo '<option value="'.$v["shift_id"].'" '.$selected.'>'.$v["opmerking"].' - '.$bg_tijd->format('H:i').' t/m '.$ed_tijd->format('H:i').'</option>';
                                            }
                                            ?>
                                        </select>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <th>Opmerking:</th>
                                <td><i><?= $r["opmerking"] ?></i></td>
                            </tr>
                            <tr>
                                <th>Tafel nummer:</th>
                                <td>
                                    <div class="input-field" style="margin-bottom: -30px">
                                        <input type="text" style="height: 30px;"  maxlength="10" data-length="10" style="height: 30px;" name="tafel_nummer" value="<?= $r["tafel_nummer"] ?>"/>
                                        <label for="icon_telephone">Hier kun je een eigen tafelnummer opgeven</label>

                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col s6">
                <div class="card"  style="height: 650px">
                    <div class="card-content">
                        <h4>Klant</h4>
                        <br />
                        <table class="table bordered">
                            <input type="hidden" name="user_id" value="<?= $r["gebruiker_id"] ?>" />
                            <tr>
                                <th><i class="material-icons">account_circle</i></th>
                                <td>
                                    <div style="margin-bottom: -30px;margin-top: -10px;">
                                        <input type="text" style="width:30%; height: 30px;" name="voornaam" value="<?= $r["voornaam"] ?>" />
                                        <input type="text" style="width:45%; height: 30px;" name="achternaam" value="<?= $r["achternaam"] ?>" />
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <th><i class="material-icons">mail</i></th>
                                <td>
                                    <div style="margin-bottom: -30px;margin-top: -10px;">
                                        <input type="text" style="width:75%; height: 30px; margin-right: 10px" name="email" value="<?= $r["email"] ?>" />
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <th><i class="material-icons">phone_iphone</i></th>
                                <td>
                                    <div style="margin-bottom: -30px;margin-top: -10px;">
                                        <input type="text" style="width:75%; height: 30px; margin-right: 10px" name="phone" maxlength="13" value="<?= $r["telefoon"] ?>" />
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <th><i class="material-icons">flag</i></th>
                                <td>
                                    <div style="margin-bottom: -30px;margin-top: -10px;">
                                        <b><?= $r["vereniging"] ?></b>
                                    </div>
                                </td>
                            </tr>
                        </table>
                        <img src="https://image.flaticon.com/icons/png/512/10/10991.png" style="position: absolute; bottom: -40px; right: 0; width: 300px" />
                    </div>
                </div>
            </div>
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                            <input type="submit" name="Opslaan" value="opslaan" class="btn  red orange darken-2 right"/>
                            <a href="reservering/bekijken/<?= $_GET["id"] ?>" class="btn-flat right">ANNULEREN</a>
                        <div style="clear:both"></div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>