<nav>

    <a href="/pages/home"><div id="brand"><img src="/template/images/icons/icon_happietaria.png" height="100%"/></div></a>
    <ul>
        <li><a href="reservering/nieuw">RESERVEREN</a></li>
        <li><a href="crew/nieuw">MEEHELPEN</a></li>
        <li><a href="pages/project">PROJECT</a></li>
        <li><a href="pages/sponsoring">SPONSORING</a></li>
        <li><a href="pages/contact">CONTACT</a></li>
    </ul>
    <ul class="right">
        <li><a href="https://www.facebook.com/happietariazwolle/" target="_blank"><img src="/template/images/icons/facebook_nav.png" height="30px" /></a></li>
    </ul>
</nav>