<nav>

    <a href="pages/home"><div id="brand">Happietaria</div></a>
    <ul>
        <li><a href="pages/project">PROJECT</a></li>
        <li><a href="reservering/nieuw">RESERVEREN</a></li>
        <li><a href="#sample">CONTACT</a></li>
        <li><a href="pages/sponsoring">SPONSORING</a></li>

    </ul>
    <ul class="right">
        <li><a href="pages/inloggen">INLOGGEN</a></li>
    </ul>
</nav>