<?php
    $s = $this->obj->data["shift"];
?>
<br>
<br>
<br>
<form action="" method="post" class="container">
    <div class="row">
        <div class="col s7">
            <div class="input-field">
                <input type="text" class="validate" name="opmerking" value="<?= $s["opmerking"]?>">
                <label>Caption</label>
            </div>
            <div class="input-field">
                <input type="text" name="begin_tijd" class="timepicker" value="<?= $s["begin_tijd"]?>">
                <label>Begin tijd</label>
            </div>
            <div class="input-field">
                <input type="text" name="eind_tijd" class="timepicker" value="<?= $s["eind_tijd"]?>">
                <label>Eind tijd</label>
            </div>
        </div>
        <div class="col s5"></div>
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <input type="submit" name="Opslaan" value="opslaan" class="btn  red orange darken-2 right"/>
                    <a href="/shift/index" class="btn-flat right">ANNULEREN</a>
                    <div style="clear:both"></div>
                </div>
            </div>
        </div>
    </div>
</form>