<?php
    $i =  $this->obj->data["inschrijving"];

    $afdeling = '';
    $diploma = '';

    foreach($this->obj->data["skills"] as $s){

        if($s["type"] == 1){ $afdeling .= '- '. $s["vaardigheid"].'<br />'; } else{ $diploma .= '- '. $s["vaardigheid"].'<br />'; }
    }
?>
<br />
<div class="container">
    <div class="row">
        <div class="fixed-action-btn horizontal">
            <a class="btn-floating btn-large red">
                <i class="large material-icons">build</i>
            </a>
            <ul>
                <li><a href="crew/sendmail/<?= $_GET["id"]  ?>" class="btn-floating green tooltipped" data-position="top" data-delay="50" data-tooltip="Vrijwilliger mailen"><i class="material-icons">email</i></a></li>
            </ul>
        </div>
        <div class="col s6">
            <div class="card" style="height: 650px">
                <div class="card-content">
                    <h4>Voorkeur  </h4>
                    <br />
                    <table class="table bordered">
                        <tr>
                            <th valign="top">Gekozen taken:</th>
                            <td><?= $afdeling ?></td>
                        </tr>
                        <tr>
                            <th valign="top">Gekozen diploma's:</th>
                            <td><?= $diploma ?></td>
                        </tr>
                        <tr>
                            <th valign="top">Gekozen dagen:</th>
                            <td><?= $i["beschikbaar"] ?></td>
                        </tr>
                        <tr>
                            <th valign="top">Opmerking:</th>
                            <td><i><?= $i["opmerking"] ?></i></td>
                        </tr>
                        <tr valign="top">
                            <th valign="top">Status:</th>
                            <td>
                                <p>
                                    <input name="status" readonly disabled type="radio" id="state1" <?= ($i["active"] == 1 && $i["contact_gehad"] == 0) ? "checked" : "" ; ?>/>
                                    <label for="state1">Nieuw</label>
                                </p>
                                <p>
                                    <input name="status" readonly disabled type="radio" id="state2" <?= ($i["active"] == 1 && $i["contact_gehad"] == 1) ? "checked" : "" ; ?>/>
                                    <label for="state2">Bekeken</label>
                                </p>
                                <p>
                                    <input name="status" readonly disabled type="radio" id="state3"  <?= ($i["active"] == 0) ? "checked" : "" ; ?>/>
                                    <label for="state3">Verwijderd</label>
                                </p>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col s6">
            <div class="card"  style="height: 650px">
                <div class="card-content">
                    <h4>Vrijwilliger</h4>
                    <br />
                    <table class="table bordered">
                        <tr>
                            <th><i class="material-icons">account_circle</i></th>
                            <td><?= $i["voornaam"] ?> <?= $i["achternaam"] ?></td>
                        </tr>
                        <tr>
                            <th><i class="material-icons">mail</i></th>
                            <td><?= $i["email"] ?></td>
                        </tr>
                        <tr>
                            <th><i class="material-icons">phone_iphone</i></th>
                            <td><?= $i["telefoon"] ?></td>
                        </tr>
                        <tr>
                            <th><i class="material-icons">flag</i></th>
                            <td>
                                <div style="margin-bottom: -30px;margin-top: -10px;">
                                    <b><?= $i["vereniging"] ?></b>
                                </div>
                            </td>
                        </tr>
                    </table>
                    <img src="https://image.flaticon.com/icons/png/512/10/10991.png" style="position: absolute; bottom: -40px; right: 0; width: 300px" />
                </div>
            </div>
        </div>
        <div class="col s12">
            <div class="card">
                <div class="card-content">
                    <a href="crew/sendmail/<?= $_GET["id"]  ?>" class="btn light-blue darken-2  right" style="margin-right: 10px;">STUUR MAIL</a>
                    <a href="crew/index" class="btn-flat right"  style="margin-right: 10px;">TERUG</a>


                    <div style="clear:both"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        $('select').material_select();
    });
</script>