<div id="res_wp">
    <div class="mask">

        <div class="card" id="reservationDiv">
            <form method="post" action="">

                <h4 style="text-align: center; padding-top: 15px;">Nieuwe reservering</h4>

                <div class="card-content">
                    <?php if(!empty($this->obj->data["message"])){ ?>
                        <div class="chip">
                            <?php $icon = ($this->obj->data["message"] == "Reservering was succesvol toegevoegd") ?  "success" : "exclamation_mark" ; ?>
                            <img src="/template/images/<?= $icon ?>.png" alt="Form not filled in correctly">
                            <?= $this->obj->data["message"] ?>
                            <i class="close material-icons">close</i>
                        </div>
                    <?php } ?>
                    <h5>Persoonlijke gegevens</h5>
                    <div class="row">
                        <div class="input-field col s6">
                            <i class="material-icons prefix">account_circle</i>
                            <input id="icon_prefix" name="voornaam" type="text" class="validate" maxlength="20" data-length="20" required value="<?php if(isset($_POST["voornaam"])){echo $_POST["voornaam"];} ?>">
                            <label for="icon_prefix">Voornaam</label>
                        </div>
                        <div class="input-field col s6">
                            <input id="icon_prefix" name="achternaam" type="text" class="validate" maxlength="40" data-length="40" required value="<?php if(isset($_POST["achternaam"])){echo $_POST["achternaam"];} ?>">
                            <label for="icon_prefix">Achternaam</label>
                        </div>
                        <div class="input-field col s12">
                            <i class="material-icons prefix">email</i>
                            <input id="text" type="email" name="email" class="validate" maxlength="50" data-length="50"  required value="<?php if(isset($_POST["email"])){echo $_POST["email"];} ?>">
                            <label for="icon_telephone">Email adres</label>
                        </div>
                        <div class="input-field col s12">
                            <i class="material-icons prefix">phone_iphone</i>
                            <input id="text" type="text" name="telefoon" maxlength="15" data-length="15"  class="validate" value="<?php if(isset($_POST["telefoon"])){echo $_POST["telefoon"];} ?>">
                            <label for="icon_telephone">Telefoon nummer (optioneel)</label>
                        </div>
                        <div class="input-field col s12">
                            <i class="material-icons prefix">flag</i>
                            <select class="form-control" name="vereniging">
                                <?php
                                foreach($this->obj->data["verenigingen"] as $v){
                                    $selected = ($v["vereniging_id"] == $_POST["vereniging"]) ? "selected" : "";
                                    echo '<option value="'.$v["vereniging_id"].'" '.$selected.'>'.$v["naam"].'</option>';
                                }
                                ?>
                            </select>
                            <label for="icon_telephone">Vereniging</label>
                        </div>
                    </div>

                    <div class="row">

                    </div>
                </div>
                <div class="card-action">
                    <button type="submit" class="waves-effect waves-light btn right green darken-1" >RESERVERING AANMAKEN</button>
                    <a href="/pages/home" class="waves-effect waves-teal btn grey lighten-1">ANNULEREN</a>
                </div>
            </form>
        </div>

    </div>

</div>

<script>
    $(document).ready(function() {
        $('select').material_select();
    });
    $('.datepicker').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 15, // Creates a dropdown of 15 years to control year,
        today: 'Today',
        clear: 'Clear',
        close: 'Ok',
        closeOnSelect: false // Close upon selecting a date,
    });
    $('.timepicker').pickatime({
        default: 'now', // Set default time: 'now', '1:30AM', '16:30'
        fromnow: 0,       // set default time to * milliseconds from now (using with default = 'now')
        twelvehour: false, // Use AM/PM or 24-hour format
        donetext: 'OK', // text for done-button
        cleartext: 'Clear', // text for clear-button
        canceltext: 'Cancel', // Text for cancel-button
        autoclose: false, // automatic close timepicker
        ampmclickable: true, // make AM PM clickable
        aftershow: function(){} //Function for after opening timepicker
    });
</script>