<div id="res_wp">
    <div class="mask">
        <div class="card" id="reservationDiv">
            <h4 style="text-align: center; padding-top: 15px;">Contact</h4>
            <br /><br />
            <div class="row">

                <div class="col s6">
                    <p><b>About</b><br />Heeft u vragen, opmerkingen of tips? Laat het ons weten!</p>
                    <table class="table bordered">

                        <tr>
                            <th><i class="material-icons">mail</i></th>
                            <td>+31 6 512 221 04</td>
                        </tr>
                        <tr>
                            <th><i class="material-icons">phone_iphone</i></th>
                            <td><a href="mailto:info@happietaria-zwolle.nl">info@happietaria-zwolle.nl</a></td>
                        </tr>

                    </table>
                    <br />

                </div>
                <div class="col s6">
                    <b>Commissie Van Aanbeveling</b><br />
                    <ol>
                        <li>Drs. J.D. Schaap, voorzitter college van bestuur Hogeschool Viaa.</li>
                        <li>Dhr. Henk Jan Meijer, burgermeester Zwolle.</li>
                        <li>Mevr. I. Grimm, lid college van Bestuur Hogeschool Windesheim.</li>
                        <li>Dhr. H. Hagoort, voorzitter College van Bestuur Hogeschool Windesheim</li>
                    </ol>
                </div>
            </div>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13739.52878031237!2d6.073162260864796!3d52.50034408968292!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c7ded4e818a589%3A0x68b47bb437213d3b!2sHogeschool+Windesheim!5e0!3m2!1snl!2snl!4v1516630713167" width="100%" height="350" frameborder="0" style="border:0; padding-top: 25px;"></iframe>

        </div>

    </div>
</div>

