<section>
    <div id="decorationDiv">
        <div class="mask">
            <h4 style="text-align: center; padding-top: 15px;">Contact</h4>

        </div>
    </div>
    <div class="container">
        <br /><br />
        <div class="row">

            <div class="col s7">
                <p><b>About</b><br />Heeft u vragen, opmerkingen of tips? Laat het ons weten!</p>

                <table class="table">

                    <tr>
                        <th><i class="material-icons">mail</i></th>
                        <td>+31 6 512 221 04</td>
                    </tr>
                    <tr>
                        <th><i class="material-icons">phone_iphone</i></th>
                        <td><a href="mailto:info@happietaria-zwolle.nl">info@happietaria-zwolle.nl</a></td>
                    </tr>

                </table>
                <br />
                <b>Commissie Van Aanbeveling</b><br />
                <ol>
                    <li>Drs. J.D. Schaap, voorzitter college van bestuur Hogeschool Viaa.</li>
                    <li>Dhr. Henk Jan Meijer, burgermeester Zwolle.</li>
                    <li>Mevr. I. Grimm, lid college van Bestuur Hogeschool Windesheim.</li>
                    <li>Dhr. H. Hagoort, voorzitter College van Bestuur Hogeschool Windesheim</li>
                </ol>
            </div>
            <div class="col s5">
                <div class="card">
                    <div class="card-image">
                        <iframe style="margin-top: -10px; margin-bottom: -10px;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d607.11973199944!2d6.100079962781191!3d52.506671267662256!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c7df26cb7fae99%3A0xbf24e6ace98bdac5!2sSociaal+Culturele+Vereniging+Eureka!5e0!3m2!1snl!2snl!4v1517561200285" width="100%" height="250" frameborder="0" style="border:0; padding-top: 25px;"></iframe>
                    </div>
                    <div class="card-content">
                        <p>
                            <b>Eureka!</b>, Dit is onze trotse locatie.
                            tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc
                        </p>
                    </div>
                </div>
            </div>
        </div>


    </div>

</section>

