<br />
<div class="container">
    <div class="card">
        <div class="card-content">
            <div class="row">
                <div class="col s8">
                    <h4>Welkom terug <?= $_SESSION["gebruiker"]["voornaam"] ?></h4>

                    <p>
                        Dit is het Happietaria <i>"Content Management Systeem"</i> (afgekort CMS).<br /><Br /><b>Hier kun je:</b>
                        <ul>
                            <li>- Alle reserveringen en inschrijvingen van vrijwilligers zien</li>
                            <li>- Antwoorden op reserveringen en inschrijvingen</li>
                            <li>- Het laatste nieuws wijzigen</li>
                            <li>- De website beheren</li>
                        </ul>
                        <br />

                        Als je verder nog vragen hebt over dit systeem kun je altijd contact<br /> opnemen via <b>support@happietaria.nl</b>.
                    <br />
                    <br />
                    <br />
                    </p>
                </div>
                <div class="col s4 z-depth-3" style="padding-bottom: 8px">
                    <div class="card-content">
                        <h3>Account wijzigen</h3>
                        <div class="row">
                            <div class="input-field col s12">
                                <input value="<?= $_SESSION["gebruiker"]["email"] ?>" id="disabled" type="email" class="validate">
                                <label for="email">Email adres</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input value="" id="passwd1" type="text" class="validate">
                                <label for="passwd1">Wachtwoord</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input value="" id="passwd2" type="text" class="validate">
                                <label for="passwd2">Wachtwoord herhalen</label>
                            </div>
                        </div>
                        <input type="submit" name="Opslaan" value="opslaan" class="btn  red orange darken-2 right"/>
                        <br />
                        <br />
                    </div>



                </div>

            </div>

        </div>

    </div>
    </div>
</div>