<br />
<div class="container">
    <div class="card">
        <div class="card-content">
            <div class="row">
                <div class="col s8">
                    <h4>Welkom terug <?= $_SESSION["gebruiker"]["voornaam"] ?></h4>

                    <p>
                        Dit is het Happietaria <i>"Content Manacement Systeem"</i> (afgekort CMS).<br /><Br /><b>Hier kun je:</b>
                        <ul>
                            <li>- Alle reserveringen en inschrijvingen van vrijwilligers zien</li>
                            <li>- Antwoorden op reserveringen en inschrijvingen</li>
                            <li>- Het laatste nieuws wijzigen</li>
                            <li>- De website beheren</li>
                        </ul>
                        <br />

                        Als je verder nog vragen hebt over dit systeem kun je altijd contact<br /> opnemen via <b>support@happietaria.nl</b>.
                    <br />
                    <br />
                    <br />
                    </p>
                </div>
                <div class="col s4">
                    <h5>Laatste nieuws</h5>
                    <div class="nieuwsItem">
                        <img src="http://www.abutirams.co.za/wp-content/uploads/2016/09/Business-Consulting.jpg" />
                        <p>
                            <b>Dit is een test</b><br />
                            blablabla..
                        </p>
                    </div>
                    <div class="nieuwsItem">
                        <img src="http://www.abutirams.co.za/wp-content/uploads/2016/09/Business-Consulting.jpg" />
                        <p>
                            <b>Dit is een test</b><br />
                            blablabla..
                        </p>
                    </div>
                    <div class="nieuwsItem">
                        <img src="http://www.abutirams.co.za/wp-content/uploads/2016/09/Business-Consulting.jpg" />
                        <p>
                            <b>Dit is een test</b><br />
                            blablabla..
                        </p>
                    </div>
                    <div class="nieuwsItem">
                        <img src="http://www.abutirams.co.za/wp-content/uploads/2016/09/Business-Consulting.jpg" />
                        <p>
                            <b>Dit is een test</b><br />
                            blablabla..
                        </p>
                    </div>
                    <a href="/nieuws/overzicht" class="right">Meer nieuwsberichten</a>
                </div>

            </div>

        </div>

    </div>
    </div>
</div>