<section>
    <div id="decorationDiv">
        <div class="mask">
            <h4 style="text-align: center; padding-top: 15px;">Doneren</h4>

        </div>
    </div>
    <div class="container">
        <br /><br />

        <div id="information" class="container">
            <div id="information_card" class="card">
                <div class="card-content">

                    <br>
                    <p style="font-size: 20px;text-align: center; " class="information_paragraph">
                        Om Zuid-Sudan zelfvoorzienend te maken en hun samenleving weer op te bouwen hebben wij een bedrag van maar liefst €27.000,- nodig! Helpt u mee om dit fantastische project te realiseren?
                    </p><br /><br />
                    <div id="gauger_container" class="z-depth-4">
                        <p id="gauger_label">0/0</p>
                        <div id="gauger_volume"></div>
                    </div>
                    <br /><br />
                    <p class="information_paragraph" style="text-align: center; font-style: italic">
                        U kunt uw bijdrage overmaken naar: NL26 RABO 0320 3784 62 T.n.v. Stichting TEAR Fund Nederland
                    </p>
                </div>

            </div>
        </div>

    </div>

</section>

<script>
    $(document).ready(function(){
        $('.parallax').parallax();
    });

    $(function(){
        var goal = 27000;
        var current = 0;
        var perc = (current / goal) * 100;
        $("#gauger_volume").css("width",perc+ "%");
        current = Number(current).toLocaleString('nl');
        goal = Number(goal).toLocaleString('nl');

        $("#gauger_label").html(current + " / " + goal + " &euro;");
    });
</script>