<section>
    <div id="decorationDiv">
        <div class="mask">
            <h4 style="text-align: center; padding-top: 15px;">Doneren</h4>

        </div>
    </div>
    <div class="container">
        <br /><br />

        <div id="information" class="container">
            <div id="information_card" class="card">
                <div class="card-content">
                    <h2>
                        <i class="medium material-icons z-depth-3">insert_chart</i> Doneren
                    </h2>
                    <br>
                    <p class="information_paragraph">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.
                    </p>
                    <br>
                    <br>
                    <p class="information_paragraph">
                        U kunt uw bijdrage overmaken naar: NL26 RABO 0320 3784 62 T.n.v. Stichting TEAR Fund Nederland
                    </p>
                </div>

            </div>
        </div>

    </div>

</section>

