<section id="onsdoel">
    <div id="decorationDiv">
        <div class="mask">
            <h4 style="text-align: center; padding-top: 15px;">Ons doel</h4>

        </div>
    </div>
    <div class="container row">
        <div class="col s12 m12">
            <br /><br />
            <div class="card horizontal">
                <div class="card-image hideonmob">
                    <img src="/template/images/thumb1.jpg">
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <h4>Even in het kort</h4>
                        <p id="information_paragraph">
                            Dit jaar zet Happietaria Zwolle zich in voor een project van stichting ZOA: voedselzekerheid in Zuid-Sudan.<br /><br />
                            Dit Afrikaanse land zit in een bijna uitzichtloze situatie door een langdurige burgeroorlog, duizenden mensen ie op de vlucht zijn en een bijkomende hongersnood. Wij gaan ons inzetten om Zuid-Sudan een toekomst te bieden!
                    </div>
            </div>
        </div>
        <div class="col s12 m12">
            <br /><br />
            <div class="card horizontal" style="margin-top: -20px">
                <div class="card-image hideonmob">
                    <img src="/template/images/thumb2.jpg">
                </div>
                <div class="card-stacked">
                    <div class="card-content">
                        <p id="cvaleden_paragraph">
                            <b>CVA Leden</b><br />
                            Happietaria Zwolle heeft een Commissie Van Aanbeveling verzameld om zo onze betrouwbaarheid en professionaliteit te benadrukken. Onderstaande personen steunen ons om dit jaar een groot succes te worden en het goede doel te steunen.
                        </p>
                        <br />
                        <ul id="leden">
                            <li><i class="tiny material-icons orange-text">restaurant</i> Drs. J.D. Schaap, voorzitter college van bestuur Hogeschool Viaa.</li>
                            <li><i class="tiny material-icons orange-text">restaurant</i> Dhr. Henk Jan Meijer, burgermeester Zwolle.</li>
                            <li><i class="tiny material-icons orange-text">restaurant</i> Mevr. I. Grimm, lid college van Bestuur Hogeschool Windesheim.</li>
                            <li><i class="tiny material-icons orange-text">restaurant</i> Dhr. H. Hagoort, voorzitter College van Bestuur Hogeschool Windesheim</li>
                        </ul>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
