<section id="onsdoel">
    <div id="decorationDiv">
        <div class="mask">
            <h4 style="text-align: center; padding-top: 15px;">Ons doel</h4>

        </div>
    </div>
    <div class="container row">
        <div class="col s6">
            <div class="card ons_doel_card">
                <div class="card-content">
                    <h2>
                        <i class="medium material-icons z-depth-3">info</i> Ons doel
                    </h2>
                    <p id="information_paragraph">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui.
                    </p>
                </div>
            </div>
        </div>
        <div class="col s6">
            <div class="card ons_doel_card">
                <div class="card-content">
                    <h2>
                        <i class="medium material-icons z-depth-3">star</i> CVA leden
                    </h2>
                    <p id="cvaleden_paragraph">
                        Happietaria Zwolle heeft een Commissie Van Aanbeveling verzameld om zo onze betrouwbaarheid en professionaliteit te benadrukken. Onderstaande personen steunen ons om dit jaar een groot succes te worden en het goede doel te steunen.
                    </p>
                    <div class="row">
                        <div class="col s3"></div>
                        <div class="col s6">
                            <ul id="leden">
                                <li><i class="tiny material-icons orange-text">restaurant</i> Drs. J.D. Schaap, voorzitter college van bestuur Hogeschool Viaa.</li>
                                <li><i class="tiny material-icons orange-text">restaurant</i> Dhr. Henk Jan Meijer, burgermeester Zwolle.</li>
                                <li><i class="tiny material-icons orange-text">restaurant</i> Mevr. I. Grimm, lid college van Bestuur Hogeschool Windesheim.</li>
                                <li><i class="tiny material-icons orange-text">restaurant</i> Dhr. H. Hagoort, voorzitter College van Bestuur Hogeschool Windesheim</li>
                            </ul>
                        </div>
                        <div class="col s3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
