<footer>
    <div id="footer1">
        <div class="container row">
            <div class="col s7">
                <h4>Over ons</h4>
                <p>
                    Welkom bij Happietaria Zwolle!
                    Wij zijn een pop-up restaurant gerund door een team van studenten en vrijwilligers.
                    Een maand lang draaien wij voor een goed doel, ondersteund door stichting Tear. Wij zijn geopend van
                    17 februari tot en met 17 maart 2018.
                </p>
            </div>
            <div class="col s5">
                <h4>Contact</h4>
                <table class="table">
                    <tr>
                        <th><i class="material-icons">mail</i></th>
                        <td>+31 6 512 221 04</td>
                    </tr>
                    <tr>
                        <th><i class="material-icons">phone_iphone</i></th>
                        <td><a href="mailto:info@happietaria-zwolle.nl">info@happietaria-zwolle.nl</a></td>
                    </tr>
                </table>
            </div>
        </div>

    </div>
    <div id="footer2">
        <div class="container">
            <p>&copy; Eigendom van Happietaria 2017 - 2018</p>
        </div>
    </div>
</footer>